version: '3'
services:
  php-apache-environment:
    container_name: example-apache
    restart: "no"
    build:
      context: ./apache
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./apache/app:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: example-db
    image: mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
  phpmyadmin:
    container_name: example-phpmyadmin
    image: phpmyadmin
    restart: "no"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
